org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.62
neo_version_range=[21.1.62,)
loader_version_range=[1,)

tw_id = 6472889

mod_id=tfbr
mod_name=Twilight Forest Bosses Resurrection
mod_license=All Rights Reserved
mod_version=4.2.1
mod_group_id=com.dimas_studio.tfbr
mod_authors=DimasStudio
mod_description=This mod adds ability to respawn Twilight Forest bosses.\nAfter killing boss (Naga, Lich, Hydra, Ur-Ghast, Snow Queen) special block (pedestal) will spawn\nYou need to place a trophy of boss you killed on top of this block. Important: Trophy block must be faced north!!!\nThen you need to create a circle of specific blocks (like on sheme)\nThen just right click on the pedestal!
pack_format_number=18
